### ISSUE TITLE
Yubikey as smart card

### ISSUE THREAD

**Issue by ritesh** [bluetech/pcsc-rust#11]
Hello!

I'm trying the "list readers" example to see if I can get to the Yubikey Neo via the smart card interface. But instead I get "No readers are connected". Is this expected? 

I'm trying to port something like this: https://github.com/pyauth/exile to rust as a learning exercise.

**Comment by bluetech** [comment]
Which operating system/target are you using?

**Comment by ritesh** [comment]
I'm on macOS 10.13.6 (High Seirra). FWIW, the python code I linked to up there also does not seem to detect any yubikeys  (have a yubikey Neo and yubikey 4 plugged in) so i'm beginning to suspect this has something to do with smart card support in general. I can use the yubikey for 2FA (e.g. websites).

**Comment by bluetech** [comment]
Another question, which card reader are you using? Is it recognized as a smart card reader (may be called "CCID" if connected with USB) by the system? (I'm afraid I'm not familiar enough with macOS to say how to check this exactly.)

**Comment by ritesh** [comment]
I'm not familiar with smart cards at all, sorry. According to the vendor, the Yubikey supports smart card functionality via a "PIV" interface [1]. They provide a tool (ykman) to configure a yubikey in various modes. According to the tool, the device I have is configured for OTP, FIDO and CCID mode. As I understand it, the smartcard functionality is provided by an applet on the device. 

```
$ ykman mode                                                                                                                                                  
Current connection mode is: OTP+FIDO+CCID
Supported USB interfaces are: OTP, FIDO, CCID
```

However if i try to force reset this PIV app using the instructions provided [2], the vendor provided tool cannot read/write to it. This leads me to believe that it isn't the library at fault, but something else entirely. 

```
➜  ~ ykman list
YubiKey 4 [OTP+FIDO+CCID] Serial: [redacted]                                                                                                                                                         
➜  ~ ykman piv reset
WARNING! This will delete all stored PIV data and restore factory settings. Proceed? [y/N]: y
Resetting PIV data...
Usage: ykman [OPTIONS] COMMAND [ARGS]...
Try "ykman -h" for help.

Error: Failed connecting to the YubiKey.
```

I have another yubikey but that is work provided but i'm hesitant to reset the PIV app as I don't know what that might break. I suspect a factory reset of my personal yubikey might fix it, but will need to un-enroll it from sites that I use it for a 2nd factor. 

feel free to close the issue, or i can come back with more info on this  if I get it to work after a hard reset. 

[1] https://support.yubico.com/support/solutions/articles/15000006486-yubikey-4
[2] https://support.yubico.com/support/solutions/articles/15000008587-resetting-the-smart-card-piv-applet-on-your-yubikey

**Comment by ritesh** [comment]
I cannot explain this, but rebooting my computer after a software upgrade and then re-running
```
$ ykman reset piv # Reset the PIV application
```
works to reset the smartcard application on it. I can now run the sample code that sends APDU commands, although I don't yet understand the output. 👍

**Comment by bluetech** [comment]
Great! Let me know if you run into any issues.
