### ISSUE TITLE
Provide owned variants of Context::list_readers and Card::get_attribute

### ISSUE THREAD

**Issue by robinkrahl** [bluetech/pcsc-rust#17]
This is a bit similar to the discussion in #3.  While I agree with your argument for not returning `String` instances, I think it would make sense to provide alternatives to the `Context::list_readers` and `Card::get_attribute` methods that don’t require the user to take care of querying the buffer size and allocating the buffer.  (Having a quick look at the current users of the crate, only one of them actually re-uses the allocated buffer [[0](https://github.com/HackGT/hackgt-nfc/blob/master/src/nfc.rs#L19)] while all others only use it one time [[1](https://github.com/iqlusioninc/yubikey-piv.rs/blob/main/src/readers.rs#L31), [2](https://docs.rs/crate/healthcard_rust/0.1.1/source/src/lib.rs), [3](https://github.com/kushaldas/talktosc/blob/main/src/lib.rs#L30), [4](https://docs.rs/crate/ykoath/0.1.1/source/src/main.rs)]).

This could be implemented by making `ReaderNames` store a `Cow<'buf, [u8]>` instead of a `&'buf [u8]` and adding functions like `list_readers_owned(&self) -> Result<ReaderNames<'static>, Error>` and `get_attribute_owned(&self, attribute: Attribute) -> Result<Vec<u8>, Error>` that query the required buffer size, allocate the buffer and return an owned value.

The user could then choose whether to provide a buffer to avoid allocations, or whether to let `pcsc` take care of the buffer allocation.

What do you think?

**Comment by robinkrahl** [comment]
Sure, I’ll prepare a PR!

**Comment by robinkrahl** [comment]
> For `list_readers_owned`, we should probably just return a `Vec<CString>`. If we go with allocations, might as well make it maximally convenient.

This would mean that we cannot reuse our original buffer because splitting a vector requires re-allocation (at least for the split-off part).  So instead of one allocation for all *n* strings, we would have *n* allocations.  Do you still prefer returning a vector?

**Comment by bluetech** [comment]
Yes, I think most users who would opt for owned would prefer it (although some users also go on and convert to `String`...). So it would just be a `collect()` of the non-owned function (after finding the length).

**Comment by robinkrahl** [comment]
Well, I would be a user who does not want to allocate the buffer because I cannot reuse it, but would also like to avoid unnecessary allocations. ;)  But I can also live with returning a vector.

I think this also means that we have to duplicate the `CardStatus` struct (instead of just using it with `'static` lifetimes).
