### ISSUE TITLE
Better file hierarchy

### ISSUE THREAD

**Issue by Artefaritaj** [bluetech/pcsc-rust#2]
Hi! You did a pretty good job with this library and I want to use it in my own code. So here is my frinedly 2 cents on how you can improve this lib from my personal standpoint.

You have all your lib code in one file (pcsc/src/lib.rs). It would be easier to explore your code if you stick with the principle one file per logical unit, i.e. context.rs, card.rs, ....
Additionnally, you get finer git management.

**Comment by bluetech** [comment]
Thanks for the suggestion.

Since the code is so short, I actually prefer having it all in one file; for me it is easier to read and navigate. So my inclination is to leave it as-is. However if it becomes bigger it will make sense to split.

**Comment by Artefaritaj** [comment]
You're the boss ;)
