### ISSUE TITLE
Question: Can this project be used in a WebAssembly

### ISSUE THREAD

**Issue by kaoh** [bluetech/pcsc-rust#20]
I'm not familiar with the sand boxing model web assemblies are imposing. Do you know if I can use this project also in a web assembly for accessing a smart card reader?

**Comment by bluetech** [comment]
WebAssembly itself is just an instruction set, which needs some binding to a host system to talk to hardware like smartcards. By your question I assume that you mean using WebAssembly on the web, as in a website. If so, the answer is no - the web does not offer any PC/SC or similar API.

The related APIs that the web does offer are:

- [Web NFC](https://web.dev/nfc/) - this allows communicating with NFC tags, but only with the high-level NDEF protocol (you can't send arbitrary APDUs directly).

- [Web USB](https://web.dev/usb/) - this allows communicating with USB devices, which is what most card readers are. Unfortunately last time I checked the smartcard USB class (CCID) wasn't included in the permitted WebUSB classes, but maybe that changed. Anyway, if you'd use this API and able to get a USB connection, you'll need to implement the [CCID protocol](https://usb.org/sites/default/files/DWG_Smart-Card_CCID_Rev110.pdf) but it should work.

**Comment by bluetech** [comment]
Right. It's been a while since I tried WebUSB so I don't know its current state.

**Comment by kaoh** [comment]
At the first glance I have not found a [section](https://wicg.github.io/webusb/#abusing-a-device) limiting the device class, vendor or product id. Can you remember which part was not whitelisting CCID?

**Comment by kaoh** [comment]
I get as a result an empty array. Based on this finding I guess a web assembly is not what is matching my goals.
