### ISSUE TITLE
list_readers returning NoService error after restarting pcsc service

### ISSUE THREAD

**Issue by CountryTk** [bluetech/pcsc-rust#21]
When starting my program with the pcsc service enabled, everything works fine but when I restart the pcsc service while my actix server is running and listening then `list_readers` returns a NoService error and never recovers from it (as in it never finds the service again)

What could be the cause of this? My actix server?

**Comment by bluetech** [comment]
Which operating system are you using?

**Comment by CountryTk** [comment]
Currently using Linux (Ubuntu) and restarting the service with `sudo systemctl restart pcsc.socket`

**Comment by bluetech** [comment]
Is there a reason to restart the socket instead of `sudo systemctl restart pcsc.service` (the service)?

**Comment by bluetech** [comment]
Hmm pcsclite client must not be able to handle this gracefully on its own then.

Are you able to check if [`context.is_valid()`](https://docs.rs/pcsc/2.6.0/pcsc/struct.Context.html#method.is_valid) returns false in this state?

**Comment by CountryTk** [comment]
`context.is_valid()` returns `Ok(())` when I started my program with the service running and it also returns the same thing when I restart the service during program running.

**Comment by bluetech** [comment]
Too bad, I was hoping you could detect this.

Reading pcsclite's code, it unfortunately doesn't handle this - if the connection to the service is gone (returns EPIPE in this case) it doesn't try to reestablish it. So I think the only way to handle this is to reestablish the pcsc context upon receiving this error. If you can do this, it's probably best. If not, you might want to reach out to the pcsclite devs with your use case ([mailing list](http://lists.infradead.org/mailman/listinfo/pcsclite-muscle), [github](https://github.com/LudovicRousseau/PCSC/issues)).

**Comment by CountryTk** [comment]
Thank you for this insight though, now I know what my next steps should be. I think I will close the issue since it's kind of out of scope for this crate. Thank you again though!
