### ISSUE TITLE
list_readers() -> Vec<String>

### ISSUE THREAD

**Issue by Artefaritaj** [bluetech/pcsc-rust#3]
I continue with my remarks:
You try to avoid String allocation for *ReaderNames*. Why is that?
From an ergonomic point of view, I as a user, would find it simpler to have
```
let readers: Vec<String> = ctx.list_readers();
```
This way:
- I cannot mess up with the buffer size
- I dont have to deal with CString in my rust code
- I get all the Vec niceties for free
- I dont see a use case (but I may be wrong) where avoiding  the String allocations has signifiant impact on performances (one time allocation, fast compared to smartcard i/o).

**Comment by bluetech** [comment]
To implement the signature `Vec<String> = ctx.list_readers()` you need to:

1. Allocate a buffer for the underlying `SCardListReaders` call - this is the length of all reader names + nul delimeters + final nul.
2. Count how many readers were received.
3. Allocate a vector to that length.
4. Allocate a `String` for each reader and add it the vector.

This is a lot of things most library users would not need. For example, if you want to use such an API for a monitor (as is implemented in `examples/monitor.rs`), you need to all of the above for each loop iteration. With the existing API, you allocate a buffer once and reuse it for each iteration, without further allocations.

Second, what PCSC gives us is a C string; converting it to a `String` imposes restrictions on its content (UTF-8). I hence encourage all users to just keep reader names as C strings and not convert it to `String` unless absolutely necessary.

Finally, getting a `Vec` of reader names is still pretty easy (ignoring errors), yet everything I mentioned above is explicit:

```
let mut readers_buf = [0; 2048];
let names = ctx.list_readers(&mut readers_buf).unwrap().map(|name| name.to_str().unwrap()).collect<Vec<_>>();
```

This can be done in a helper method or even an extension trait.

So this is why I settled on the current API.

**Comment by bluetech** [comment]
One more point I forgot: if I make `list_readers` return `String`s, then `ReaderState::new()` ought also to take `String`, since the argument naturally comes from `list_readers`. But `String` -> `CString` is also fallible (since `String` can contain nuls), so I would need to add an error for this case. Up to now, I managed to only return PCSC errors, not adding any error cases of my own.

**Comment by Artefaritaj** [comment]
You have indeed an interesting use case but the allocation does not take seconds: you wouldn't notice any difference because all possible actions (smartcard i/o, (un)pluging a reader) are so slow with respect to your computer.
For the conversion, I agree it introduces errors you do not want to deal with. A solution, that would additionally better communicate intent would be:
```
struct Reader {
    fancy_name: String,
    pcsc_name: CString
}
```
Either cases, you are right to say that a simple helper can do the trick.
Thank you for your answers!
