### ISSUE TITLE
Allow to pass a null() to the fn controll (send a command directly to the reader)

### ISSUE THREAD

**Issue by michallis** [bluetech/pcsc-rust#32]
In our use case we need to execute a 3400 control on the card, where we don't have a send_buffer. 
The send_buffer expects a &[u8], but when passing an empty [u8] an error is thrown (BAD EXCEPTION)

![image](https://user-images.githubusercontent.com/1217411/173229208-456d953d-e8c2-4b4d-8bd1-c2dbb060b66b.png)

```
    pub fn control<'buf>(
        &self,
        // TODO: This is a portability hazard -- should change to u32
        //       in the next breaking change release.
        control_code: DWORD,
        send_buffer: &[u8],
        receive_buffer: &'buf mut [u8],
    ) -> Result<&'buf [u8], Error> {
        let mut receive_len: DWORD = DUMMY_DWORD;

        unsafe {
            assert!(send_buffer.len() <= std::u32::MAX as usize);
            assert!(receive_buffer.len() <= std::u32::MAX as usize);

            try_pcsc!(ffi::SCardControl(
                self.handle,
                control_code,
                send_buffer.as_ptr(),
                send_buffer.len() as DWORD,
                receive_buffer.as_mut_ptr(),
                receive_buffer.len() as DWORD,
                &mut receive_len,
            ));

            Ok(&receive_buffer[0..receive_len as usize])
        }
    }
```

**Comment by bluetech** [comment]
Indeed, I had missed that `SCardControl` accepts nulls for `send_buffer` and `receive_buffer`. We should add a `control2` function which handles it correctly (and also fixes the TODO), and deprecate `control`.

If you'd like to send a PR for this, that'd be great, if not, I will get to it hopefully soon.

**Comment by michallis** [comment]
Thanks for your response, I was working on a PR for this, taking into account the TODO, but whith my CCID reader, I tried to send a 0x3400 with a ptr:null() for the send_buffer, but without success, I guess the LPCVOID mapped on a *const u8 can be an issue?

**Comment by bluetech** [comment]
Can you show the branch, even if it doesn't work? I can take a look and suggest why it's not working.

**Comment by bluetech** [comment]
Looking at pcsclite code (used on Linux and Mac), we don't really need to support NULL explicitly since it's equivalent to passing zero-length buffers, i.e.

```
card.control(ctl_code(0), &[], &mut [])
```

is entirely equivalent to passing NULL to the send/receive buffers.

On Windows I of course don't have the source code, but I tend to think it's the same (i.e. no special codes path for NULL as opposed to 0-length). So I'll close this issue, but let me know if you find I got it wrong.

**Comment by michallis** [comment]
Using &[] did not work on Mac OS nor Windows. This is working though:
`let nil = BytesMut::with_capacity(0);
match card.control(ctl_code(ctrl.into()), nil.as_ref(), &mut rapdu_buf) { ... }
`
