### ISSUE TITLE
Broken Link on page - 7816 Part 4, replace with direct link to standard, not vendor

### ISSUE THREAD

**Issue by blockcowboy** [bluetech/pcsc-rust#42]
https://docs.rs/pcsc/latest/pcsc/

Suggest you redirect to ISO standard and not vender URL.

Vendor Link Broken: http://www.cardwerk.com/smartcards/smartcard_standard_ISO7816-4.aspx

ISO Standard Link: https://www.iso.org/obp/ui/#iso:std:iso-iec:7816:-4:ed-4:v1:en

**Comment by hcldan** [comment]
This looks like the new link: https://cardwerk.com/iso-7816-part-4/

**Comment by bluetech** [comment]
Yeah, the ISO standards are not open so it's not very useful to link to them. I'll update to the new link provided by @hcldan (thanks!).
