### ISSUE TITLE
How to mock a Card

### ISSUE THREAD

**Issue by Fethbita** [bluetech/pcsc-rust#50]
Hi, I am writing an application that uses pcsc and I have a struct that holds a Card. Some functions of this struct use card.transmit to send and receive APDUs and process them. I would like to be able to mock Card so that I can test these processing functions. What do you use for mocking Card?

**Comment by bluetech** [comment]
It mostly depends, do you care about the actual APDUs/RAPDUs i.e. do you want to simulate the logic of an actual card, or do you just need some dummy for tests?

**Comment by Fethbita** [comment]
I only need a dummy for tests to begin with.

**Comment by Fethbita** [comment]
Is not an issue. I fixed is as in the PR (https://github.com/Fethbita/emrtd/pull/4) and as in the issue (https://github.com/Fethbita/emrtd/issues/2) recommended by dishmaker.
