### ISSUE TITLE
Don't force the native macOS framework

### ISSUE THREAD

**Issue by ForsakenHarmony** [bluetech/pcsc-rust#52]
Please provide a way to override which dynlib / framework `pcsc-sys` links to.

I'm trying to work with desfire cards and the native frameworks seems to still have an issue that makes it impossible which was fixed in 2010 in `pcsc-lite`:
https://github.com/LudovicRousseau/PCSC/blob/d688f7ed515f62d0edaffd1b3cc9cdbe459ddae5/ChangeLog#L739C1-L741C11

**Comment by bluetech** [comment]
Does non-builtin pcsc-lite actually work on macOS? It doesn't conflict with the built-in framework/daemon?

**Comment by ForsakenHarmony** [comment]
you can kill the built-in daemon and run your own
