### ISSUE TITLE
Calling convention should be `stdcall` on windows

### ISSUE THREAD

**Issue by ndusart** [bluetech/pcsc-rust#6]
Winscard use `stdcall` convention either for windows 32 or 64 bits.

The problem is that `system` convention use `cdecl` for windows 64 bits and we cannot use this library on Windows 64 bits then.

**Comment by bluetech** [comment]
Thanks for the report!

Can you describe how exactly it fails? Does it crash? Does it return a particular error? Just works incorrectly? I'd like to try write a test for it to run on AppVeyor, if possible. My silly attempt here https://github.com/bluetech/pcsc-rust/commit/cbe25f320bdbadbbbabe5c39ab78c35baf8ab3bd passes on AppVeyor x86_64-pc-windows-msvc, though it might just be it skips.

**Comment by bluetech** [comment]
Did a little research:

I checked what `winapi` does (assuming it's correct) -- it uses `system` as well: https://github.com/retep998/winapi-rs/blob/ad224c13346b12ecc565d6333e5c2cf890360e20/src/um/winscard.rs#L28

But looking at the header file on windows (from the only source I could find online):
https://github.com/amree/omnikey-mifare-samples-libraries/blob/master/Include/winscard.h
the functions are annotated with `WINAPI`, which according to https://msdn.microsoft.com/en-us/library/bb687850.aspx#sectionSection2 means `stdcall`.

On the other hand, according to https://doc.rust-lang.org/book/first-edition/ffi.html#foreign-calling-conventions, `system` in Rust means `stdcall` on Windows 32 (good) and `C` on Windows 64 (not good). So exactly like you said in your comment. Seems winapi is also wrong.

Anyway I'll wait for a reply on my first question.

**Comment by bluetech** [comment]
But according to https://msdn.microsoft.com/en-us/library/zxk0tw93.aspx, `__stdcall` is ignored in x64:

> On ARM and x64 processors, __stdcall is accepted and ignored by the compiler; on ARM and x64 architectures, by convention, arguments are passed in registers when possible, and subsequent arguments are passed on the stack.

So seems to me like `system` is correct after all.

**Comment by ndusart** [comment]
Sorry I didn't test it well, forcing the convention to `stdcall` does not change a thing.
Indeed, `system` seems correct as I do not have any problem with a lot of functions from `winapi` crate.

Sorry for the misnamed issue then, but I still have an issue on windows x86_64.
It's strange, I'm writing a wrapper around `pcsc-rust` for a higher-level library to smart-card (with expected support for android and iOS) and I wrote a small example that is close to your `monitor.rs` example. (I don't have my Windows machine here, but I'll test it on this specific example but I expect to be the same behaviour).

When I run my example, all is fine on Windows 32 bits, linux and MacOS. But in windows 64bits, `list_readers` always returns a reader even if there is none connected. Then `get_status_change` returns `0x6` and the library panics because this error code is not valid.
The `get_status_change` returns that invalid code even if the reader is plugged in and that the returned name is correct.

Does the example `monitor.rs` run successfully on Windows 64 bits on your side ?

**Comment by ndusart** [comment]
I find the cause of the issue.

Actually, it's the definition of `SCARDHANDLE` and `SCARDCONTEXT` that are wrong on Windows. It's not `LONG` but a pointer (so effectively 64 bits on windows 64 and not 32 as long).

My program is running correctly on all platforms now.

The error code `6` is for `ERROR_INVALID_HANDLE` but I do not know why other functions could return `SCARD_S_SUCCESS` while the handle to the context is wrong...

I opened the PR #7  for fixing this issue :)
